### ISSUE TITLE
Convert CSS to Sass

### ISSUE THREAD

**Issue by philschanely** [NateHiser/web3_proj1_repo#2]

**Comment by philschanely** [comment]
Good start here but more work to do to make full use of Sass:
- Make more use of variables to reduce repetition of common settings.
- Make more use of mixins to reduce repetition of common combinations of properties.
- Make use of nesting to reduce repetition. So a block like this:
```css
.subnav{
    background-color:#E8E8E8;
    padding-top: 20px;
    padding-bottom:60px;
}

.subnav li {
    margin-top:10px;
    padding-top:20px;
    font-size:1.8rem;
}

.subnav li li{
    margin-top:10px;
    font-size:1.4rem;
}
```
Can become
```sass
.subnav{
  background-color:#E8E8E8;
  padding-top: 20px;
  padding-bottom:60px;

  li {
    margin-top:10px;
    padding-top:20px;
    font-size:1.8rem;

    li {
      margin-top:10px;
      font-size:1.4rem;
    }
  }
}
```
- Break up the single Sass file into several smaller files as shown in the videos.

I've reorganized things a bit into a `src` folder that and added `package.json` with some things to batch sass watch and browser sync. So pull my latest commits here and the in termainl inside your project root folder run `npm install` once. After that you can just run `npm start` to fire up sass watch and browser-sync.
